FROM node:20-alpine

WORKDIR app

COPY package*.json ./

RUN npm install

COPY tsconfig*.json index.html vite.config.ts ./

COPY src ./src

COPY public ./public


EXPOSE 80


ENTRYPOINT ["npm", "run", "dev", "--","--host", "--port", "80"]
 
